#!/usr/bin/env bash
# Build a single-item Sparkle appcast for a release dmg.
#
# usage: generate-appcast.sh <dmg> <version> <download-url> <output.xml>
# Requires SPARKLE_ED_PRIVATE_KEY in the environment (base64 EdDSA seed,
# generated by scripts/generate-sparkle-keys.py).
#
# The app's SUFeedURL points at releases/latest/download/appcast.xml, so each
# release only needs to describe itself — GitHub's "latest" redirect does the
# rest.
set -euo pipefail

DMG="$1"
VERSION="$2"
URL="$3"
OUT="$4"

SIG_ATTRS="$(python3 "$(dirname "${BASH_SOURCE[0]}")/sign_update.py" "$DMG")"
PUB_DATE="$(LC_ALL=C date -u '+%a, %d %b %Y %H:%M:%S +0000')"

cat > "$OUT" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>Email</title>
    <item>
      <title>${VERSION}</title>
      <pubDate>${PUB_DATE}</pubDate>
      <sparkle:version>${VERSION}</sparkle:version>
      <sparkle:shortVersionString>${VERSION}</sparkle:shortVersionString>
      <sparkle:minimumSystemVersion>10.13</sparkle:minimumSystemVersion>
      <link>https://github.com/emmut/email/releases/tag/v${VERSION}</link>
      <enclosure url="${URL}" ${SIG_ATTRS} type="application/octet-stream"/>
    </item>
  </channel>
</rss>
EOF

echo "Wrote $OUT:"
cat "$OUT"
